tweet/post/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index,name="post"),
    path('add/', views.add_post,name="add_post"),
    path('<int:post_id>/edit/', views.edit_del_post,name="edit_post"),
    path('register/', views.register,name="register"),
]

tweet/tweet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tweet/post/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,related_name="posted_by_user",on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    content = models.TextField()
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title[0:30]}... by {self.user.username}"

tweet/post/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','image']
        labels = {
            'title': 'Post Title',
            'content': 'Post Description',
            'image': 'Upload an Image',
        }

tweet/post/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by()
    return render(request, 'index.html',{'posts': posts})

@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            print(post)
            post.save()
            return index(request)
    else:
        form = PostForm()
    return render(request, 'add_post.html', {'form': form})

@login_required
def edit_del_post(request,post_id):
    post = get_object_or_404(Post, pk=post_id,user = request.user)

    
    if request.method == 'GET' and 'delete' in request.GET:
        post.delete()
        return index(request)


    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            print(post)
            post.save()
            return index(request)
    else:
        form = PostForm(instance=post)
    return render(request, 'add_post.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
    else:
        form = UserCreationForm()
    return render(request,'registration/register.html', {'form': form})

tweet/post/templates/add_post.html
{% extends "layouts/masterLayout.html" %} {% block content %}
<section class="my-5">
  <div class="container">
    <div class="row justify-content-center">
      <h1 class="border-bottom pb-2 mb-5">
        {% if form.instance.pk %}
            Edit the post
        {% else %}
            Add a new post
        {% endif%}
      </h1>
        {% if form.instance.pk %}
            <a
              href="{% url 'edit_post' form.instance.pk %}?delete=true"
              onclick="return confirm('Are you sure you want to delete this post?')"
                class="text-end"
              >
            <button class="btn btn-danger">
                Delete
            </button>
              
            </a>
        {% endif%}
      <form
        method="post"
        enctype="multipart/form-data"
        class="col-6"
      >
        {% csrf_token %}

        <div class="form-group my-3">
          <label
            for="id_title"
            class="form-label"
            >Post Title</label
          >
          <input
            type="text"
            class="form-control"
            name="title"
            value="{{ form.title.value|default_if_none:'' }}"
          />
          {% if form.title.errors %}
          <span class="text-danger">{{ form.title.errors }}</span>
          {% endif %}
        </div>

        <div class="form-group my-3">
          <label
            for="id_content"
            class="form-label"
            >Post Content</label
          >
          <textarea
            class="form-control"
            name="content"
            id="id_content"
          >
{{ form.content.value|default_if_none:'' }}</textarea
          >
          {% if form.content.errors %}
          <span class="text-danger">{{ form.content.errors }}</span>
          {% endif %}
        </div>
        <div class="form-group my-3">
            {% if form.instance.pk %}
                <img src="{{form.instance.image.url}}" class="mb-2" alt="previous Image">
            {% endif%}
            

          <label
            for="id_image"
            class="form-label"
            >Upload Image</label
          >
          <input
            type="file"
            class="form-control"
            name="image"
            id="id_image"
          />
          {% if form.image.errors %}
          <span class="text-danger">{{ form.image.errors }}</span>
          {% endif %}
        </div>

        <button
          type="submit"
          class="btn btn-primary"
        >
          Submit Post
        </button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

tweet/post/templates/index.html
{% extends "layouts/masterLayout.html" %} {% block content %}
<section class="my-5">
  <div class="container">
    <div class="row">
      <h1 class="border-bottom pb-2">All Blogs</h1>
        <a href="{% url "add_post" %}" class="mt-3 mb-5">
            <button class="btn btn-sm btn-primary">
                Add New Post
            </button>
        </a>
      {% for post in posts %}

      <div class="col-lg-4">
        
        {% if post.user == user %}
        <a href="{% url "edit_post" post.id %}" >
            <div class="card">
              <img
                width="100%"
                height="225"
                src="{{post.image.url}}"
                class="card-img-top"
                style="object-fit: cover"
                alt="post image"
              />
              <div class="card-body">
                <h2 class="card-title">{{post.title}}</h2>
                <p class="card-text">{{post.content|slice:":30"}}...</p>
              </div>
            </div>
          </a>
        {% else  %}
            <div class="card">
              <img
                width="100%"
                height="225"
                src="{{post.image.url}}"
                class="card-img-top"
                style="object-fit: cover"
                alt="post image"
              />
              <div class="card-body">
                <h2 class="card-title">{{post.title}}</h2>
                <p class="card-text">{{post.content|slice:":30"}}...</p>
              </div>
            </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

tweet/templates/layouts/masterLayout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <title>Home Page</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />

    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <header class="border-bottom">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a
            class="navbar-brand"
            href="#"
            >Tweet</a
          >
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="collapse navbar-collapse justify-content-end"
            id="navbarSupportedContent"
          >
            <ul class="navbar-nav mb-2 mb-lg-0">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{% url "post" %}"
                  >Home</a
                >
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock  %}

  </body>
</html>